<?php
// $Id$

/**
 * @file
 * Display usage statistics in various places
 * @author Bèr Kessel <ber@webschuur.com>
 * @link http://wizzlern.nl
 * @package stats_view
 */

/* -----------------------------------------------------------------
  Hook Implementations
------------------------------------------------------------------ */
/**
 * Implementation of hook_menu().
 */
function stats_view_menu() {
  $items = array();

  $items['stats_view'] = array(
    // @TODO Add title and callback for this menu item.
    'access arguments' => array('access administration pages'), //Komen we later op terug.
  );
  
  // @TODO Add Menu item which responds to admin/settings/stats_view
  //       and calls stats_view_settings().

  return $items;
}

/**
 * Callback for hook_menu().
 * 'page callback' => 'stats_view_list' causes this function to be ran
 * for output on the page /stats_view.
 */
function stats_view_list() {
  // @TODO return dummy text for stats view page.
}

// @TODO Write callback function for admin/settings/stats_view
//       which returns dummy text for this page.
