<?php
// $Id$

/**
 * @file
 * Display usage statistics in various places
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://wizzlern.nl
 * @package stats_view
 */

/* -----------------------------------------------------------------
  Hook Implementations
------------------------------------------------------------------ */
/**
 * Implementation of hook_menu().
 */
function stats_view_menu() {
  $items = array();

  $items['stats_view_test'] = array(
    'title' => t('View statistics for a test-path'),
    'page callback' => 'stats_view_list',
    'access arguments' => array('access content'),
  );
  
  $items['admin/settings/stats_view'] = array(
    'title' => t('View statistics'),
    'page callback' => 'drupal_get_form',
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * callback for hook_menu().
 */
function stats_view_settings($form_state) {
  $form['stats_view_amount_entries'] = array(
    '#type' => 'textfield',
    '#title' => t('Amount of entries to show'),
    '#description' => t('Provide the amount of statistics-entries that you want to show in the block with the articles.'),
    '#default_value' => variable_get('stats_view_amount_entries', 5),
    '#weight' => 1,
  );

  return system_settings_form($form);
}

/**
 * Validation callback for stats_view_settings form.
 */
function stats_view_settings_validate($form, &$form_state) {
  //print_r($form_state);
  if (!(int)$form_state['values']['stats_view_amount_entries']) {
    form_set_error('stats_view_amount_entries', 'amount must be a round number');
  }
  elseif ($form_state['values']['stats_view_amount_entries'] <= 0) {
    form_set_error('stats_view_amount_entries', 'amount must be greater then 0');
  }
}

/**
 * Test-page: a menu-callback to render a list of statistics as logged in the accesslog table.
 */
function stats_view_list() {
  $out = ''; 

  $stats_database_result = db_query("SELECT * FROM accesslog a WHERE path LIKE '%s' ORDER BY timestamp DESC LIMIT %d", $path, 10);

  while ($row = db_fetch_object($stats_database_result)) {
    $out .= "at ". format_date($row->timestamp). " host ". check_plain($row->hostname) ." visited ". check_plain($row->path) ."<br />";
  }

  return $out;
}
